version: "3.9"

services:

        web:
                image: "cp-django-app:v1"
                ports:
                        - "8000:8000"
                env_file:
                        - ".env"
                restart: always
                expose:
                        - "8000"

        nginx:
                image: "cp-nginx:v1"
                ports:
                        - "8085:80"
                depends_on:
                        - "web"
                restart: always
