apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
  - name: "8085"
    port: 8085
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
