apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: cp-django-app:v1
        envFrom:
        - configMapRef:
            name: web-config
        name: web
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
